export default Object.freeze({
    INITIALIZE:          'INITIALIZE',
    START_AUTH_FETCHING: 'START_AUTH_FETCHING',
    STOP_AUTH_FETCHING:  'STOP_AUTH_FETCHING',
    START_FEED_FETCHING: 'START_FEED_FETCHING',
    STOP_FEED_FETCHING:  'STOP_FEED_FETCHING',

    START_PROFILE_FETCHING: 'START_PROFILE_FETCHING',
    STOP_PROFILE_FETCHING:  'STOP_PROFILE_FETCHING',

    START_AVATAR_FETCHING: 'START_AVATAR_FETCHING',
    STOP_AVATAR_FETCHING:  'STOP_AVATAR_FETCHING',

    START_PROFILE_EDITING: 'START_PROFILE_EDITING',
    STOP_PROFILE_EDITING:  'STOP_PROFILE_EDITING',
});
