export default Object.freeze({
    LOGIN:         'LOGIN',
    LOGIN_SUCCEED: 'LOGIN_SUCCEED',
    LOGIN_FAILED:  'LOGIN_FAILED',

    LOGOUT:         'LOGOUT',
    LOGOUT_SUCCEED: 'LOGOUT_SUCCEED',
    LOGOUT_FAILED:  'LOGOUT_FAILED',

    AUTHENTICATE:         'AUTHENTICATE',
    AUTHENTICATE_SUCCEED: 'AUTHENTICATE_SUCCEED',
    AUTHENTICATE_FAILED:  'AUTHENTICATE_FAILED',

    SIGNUP:         'SIGNUP',
    SIGNUP_SUCCEED: 'SIGNUP_SUCCEED',
    SIGNUP_FAILED:  'SIGNUP_FAILED',
});
