export default Object.freeze({
    FETCH_POSTS:         'FETCH_POSTS',
    FETCH_POSTS_SUCCEED: 'FETCH_POSTS_SUCCEED',
    FETCH_POSTS_FAILED:  'FETCH_POSTS_FAILED',
    CLEAR_POSTS:         'CLEAR_POSTS',

    GET_POSTS: 'GET_POSTS',

    DELETE_POST:         'DELETE_POST',
    DELETE_POST_SUCCEED: 'DELETE_POST_SUCCEED',
    DELETE_POST_FAILED:  'DELETE_POST_FAILED',

    LIKE_POSTS:         'LIKE_POSTS',
    LIKE_POSTS_SUCCEED: 'LIKE_POSTS_SUCCEED',
    LIKE_POSTS_FAILED:  'LIKE_POSTS_FAILED',

    DISLIKE_POSTS:         'DISLIKE_POSTS',
    DISLIKE_POSTS_SUCCEED: 'DISLIKE_POSTS_SUCCEED',
    DISLIKE_POSTS_FAILED:  'DISLIKE_POSTS_FAILED',

    CREATE_POST:         'CREATE_POST',
    CREATE_POST_SUCCEED: 'CREATE_POST_SUCCEED',
    CREATE_POST_FAILED:  'CREATE_POST_FAILED',
});
