export default Object.freeze({
    UPDATE_PROFILE:         'UPDATE_PROFILE',
    UPDATE_PROFILE_SUCCEED: 'UPDATE_PROFILE_SUCCEED',
    UPDATE_PROFILE_FAILED:  'UPDATE_PROFILE_FAILED',

    UPDATE_AVATAR:         'UPDATE_AVATAR',
    UPDATE_AVATAR_SUCCEED: 'UPDATE_AVATAR_SUCCEED',
    UPDATE_AVATAR_FAILED:  'UPDATE_AVATAR_FAILED',

    FILL_PROFILE:  'FILL_PROFILE',
    CLEAR_PROFILE: 'CLEAR_PROFILE',
});
